project:
  type: website

website:
  title: "Sabrina's Data Science Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
about:
  template: marquee
format:
  html:
    theme: cosmo
    css: styles.css